### ISSUE TITLE
tighten up oonidevops_github policy

### ISSUE THREAD

**Issue by DecFox** [ooni/devops#21]
The `oonidevops-github` IAM user cannot run `terraform plan` due to missing DynamoDB permissions. We should extend the `ooni-devops-github` permissions policy to give sufficient access to the user to run terraform actions in the github CI

Observed here: https://github.com/ooni/devops/actions/runs/8281278038/job/22659415894#step:8:13

**Comment by hellais** [comment]
https://github.com/ooni/devops/pull/22#issuecomment-1998102888

**Comment by hellais** [comment]
done in: https://github.com/ooni/devops/pull/23
