### ISSUE TITLE
Start outlining the test environment

### ISSUE THREAD

**Issue by hellais** [ooni/devops#6]
We should start outlining the structure of the test tier, so we can start migrating services over starting from the testing environment.

As part of this we should be refactoring the current resources and terraform definitions into separate modules (following how this has been done for example for clickhouse: https://github.com/ooni/devops/pull/4)

**Comment by jbonisteel** [comment]
For Sprint starting March 11

* Review the refactor PR
* Add support for CI/CD
* Take template + reproduce for Test stage
