### ISSUE TITLE
Move oonidata and data from sysadmin to devops

### ISSUE THREAD

**Issue by DecFox** [ooni/devops#63]
We want to move `oonidata.ooni.org` and `data.ooni.org` from `ooni/sysadmin` to `ooni/devops` to make the deployment easier. While there we should also rename `oonidata.ooni.org` to something better like: `data.dev.ooni.org`. We can close this once this has been done.

- [x] migrate `oonidata.ooni.org` deployment to `ooni/devops`
- [x] migrate `data.ooni.org` deployment to `ooni/devops`
- [x] deploy jupyterhub to `data.ooni.org`
- [x] choose a more apt domain for `oonidata.ooni.org` like `data.dev.ooni.org` (making `data.ooni.org` the production)

**Comment by hellais** [comment]
This is done. As part of doing this we ended up separating the notebook server out into a different smaller machine (`notebook.ooni.org`).

Eventually oonidata.ooni.org should be re-imaged to run a fresh copy of the oonidata pipeline instance.
