### ISSUE TITLE
refactor frontend ELB to allow access to metric endpoint paths

### ISSUE THREAD

**Issue by DecFox** [ooni/devops#99]
As part of #93, we reduced the number of load balancers and got rid of the individual service domains for our aws services. We serve the metrics for these services on the root prefixed `/metric` endpoint. We should make changes to allow the frontend ELB (`dev.api.ooni.io`) to access this path on all services and if required serve on an accessible path in the service.

**Comment by hellais** [comment]
This has been implemented by adding Host based routing on the ALB rule, closes: https://github.com/ooni/devops/pull/96
